apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  namespace: sj-infra
  labels:
    app: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
      - name: influxdb
        image: harbor.192.168.50.200.sslip.io/sj-harbor/influxdb:2.7
        ports:
        - containerPort: 8086
