apiVersion: apps/v1
kind: Deployment
metadata:
  name: sj-bitcoin-collector
  namespace: sj-infra
  labels:
    app: sj-bitcoin-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sj-bitcoin-collector
  template:
    metadata:
      labels:
        app: sj-bitcoin-collector
    spec:
      containers:
      - name: sj-bitcoin-collector
        image: harbor.192.168.50.200.sslip.io/sj-harbor/bitcoin-collector:v2
        # [전문가의 팁] 환경변수를 통해 DB 접속 정보를 주입합니다.
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: INFLUXDB_URL
          value: "http://influxdb-service:8086" # K8s 내부 서비스 이름 사용
        - name: INFLUXDB_TOKEN
          value: "gtl2xtMpi-8eTP-OzRrYhZuY2Sg7WrDjFxPUhptdTmkyttUcl3_DHt8rY0sJ_thGNRpgqA4dQ3zhZ1osq2XaXg=="
        - name: INFLUXDB_ORG
          value: "infra_study"
        - name: INFLUXDB_BUCKET
          value: "bucket"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
